### ISSUE TITLE
Add to "Mined by" new pool https://hush.lucky-mining.com.ua - Ukraine/Kiev

### ISSUE THREAD

**Issue by OleksandrBlack** [MyHush/explorer.myhush.org#3]
Add to "Mined by" new pool https://hush.lucky-mining.com.ua - Ukraine/Kiev
[https://github.com/MyHush/insight-api-hush/pull/1](https://github.com/MyHush/insight-api-hush/pull/1)
Buffer('6c75636b792d6d696e696e672e636f6d2e7561', 'hex')]) // lucky-mining.com.ua

**Comment by matthewjamesr** [comment]
Is this a code change for insight-ui or on their own z-nomp end @leto?

**Comment by matthewjamesr** [comment]
@leto Added pool to `insight-api-hush`

**Comment by OleksandrBlack** [comment]
@matthewjamesr @leto  Please make a small change. I'm sorry that I was not careful.
[pull request №2](https://github.com/MyHush/insight-api-hush/pull/2)

**Comment by leto** [comment]
@matthewjamesr currently the explorer production site is running it's own fork of code, I inherited things that way. It's needs to be dealt with, to properly merge this stuff in

**Comment by OleksandrBlack** [comment]
@leto Sorry, I did not understand what you mean. I still ask you to add our pool to the explorer, since we make a significant contribution to the extraction of blocks.
![bl](https://user-images.githubusercontent.com/13917465/34342696-5e3ccb24-e9c0-11e7-9231-c8df2cef5da2.jpg)
